import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  const Subjects = [
    {
      id: 1,
      name: "Compiler Design",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/compiler-design",
    },
    {
      id: 2,
      name: "Computer Network",
      image: "https://i.ytimg.com/vi/bY5OfBrBg1M/maxresdefault.jpg",
      url: "../course/computer-network",
    },
    {
      id: 3,
      name: "Data Structure",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/data-structure",
    },
    {
      id: 4,
      name: "C with alogrithm",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/c-with-algorithm",
    },
    {
      id: 5,
      name: "Data base management system",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/data-base-management-system",
    },
    {
      id: 6,
      name: "Engineering mathmatics",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/engineering-mathmaics",
    },
    {
      id: 7,
      name: "Digital Logic",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/digital-logic",
    },
    {
      id: 8,
      name: "Operating System",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/operating-system",
    },
    {
      id: 9,
      name: "Theroy of Computation",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/theory-of-computation",
    },
    {
      id: 10,
      name: "Software engineering",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/software-engineering",
    },
    {
      id: 11,
      name: "Artifical Intelligence",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/artifical-intelligence",
    },
    {
      id: 12,
      name: "General Aptitude",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/general-aptitude",
    },
    {
      id: 13,
      name: "Discrete Mathmatics",
      image:
        "https://edurev.gumlet.io/AllImages/original/ApplicationImages/CourseFeatureImage/24f09887-9bea-45d8-b7ac-2884efeb1e30_CF.png?w=200&dpr=2.6",
      url: "../course/discrete-mathmatics",
    },
  ];

  return (
    <>
      <Head>
        <title>Gate Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div class="text-5xl font-extrabold item-center text-center">
        <span class="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
          Course
        </span>
      </div>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4">
            {Subjects.map(function (d, id) {
              return (
                <div className="list-none p-2  sm:w-1/2 md:w-1/3 " key={id}>
                  <Link href={d.url}>
                    <div className="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden cursor-pointer">
                      <img
                        className="lg:h-48 md:h-36 w-full object-center"
                        src={d.image}
                        alt="blog"
                      />
                      <div className="p-6">
                        <h1 className="title-font text-lg font-medium text-gray-900 mb-3">
                          {d.name}
                        </h1>
                        <p className="leading-relaxed mb-3">
                          Photo booth fam kinfolk cold-pressed sriracha leggings
                          jianbing microdosing tousled waistcoat.
                        </p>
                      </div>
                    </div>
                  </Link>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </>
  );
}
